<a href="https://colab.research.google.com/github/sandun7787/-CIS6003-Online-Job-Appoinment-System/blob/main/Disaster_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

In [3]:
# Read data
train_data = pd.read_csv("train.csv")
print(train_data.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [37]:
# Store test PassengerIds for later use
test_passenger_ids = test_data["PassengerId"]

In [5]:
print(train_data.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [6]:
# check nulls
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
train_data.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)


#fill null age values
train_data['Age'].fillna(train_data['Age'].mean(), inplace=True)

#fill embarked values
print(train_data['Embarked'].mode())
train_data['Embarked'].fillna(train_data['Embarked'].mode()[0], inplace=True)


train_data.head()

0    0.0
Name: Embarked, dtype: float64


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN       0.0  
1          PC 17599  71.2833   C85       1.0  
2  STON/O2. 3101282   7.9250   NaN       0.0  
3            113803  53.1000  C123       0.0  
4            373450   8.0500   NaN       0.0

In [8]:
y = train_data.Survived.copy()
train_data = train_data.drop(['Name','Ticket','Survived','Cabin'], axis=1)
train_data.head()
# Splitting train set
X_train, X_test, y_train, y_test = train_test_split(train_data, y, test_size = 0.2, random_state=123)

In [9]:
# Recheck nulls
train_data.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [10]:
# Import models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [11]:
Dt_clf = DecisionTreeClassifier()
Rf_clf = RandomForestClassifier()
LR_clf = LogisticRegression()

In [12]:
Dt_clf.fit(X_train, y_train)
Rf_clf.fit(X_train, y_train)
LR_clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
def evaluate(model, X_test, y_test):
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    # Return accuracy for later use
    return accuracy


# Now you can use the evaluate function with your models
print("DT")
DT_accuracy = evaluate(Dt_clf, X_test, y_test)

print("RF")
Rn_accuracy = evaluate(Rf_clf, X_test, y_test)

print("LR")
LR_accuracy = evaluate(LR_clf, X_test, y_test)

# Now you have the accuracy scores stored in variables for later use
print(f"DT Accuracy: {DT_accuracy:.4f}")
print(f"RF Accuracy: {Rn_accuracy:.4f}")
print(f"LR Accuracy: {LR_accuracy:.4f}")

DT
Accuracy: 0.7039
Precision: 0.7268
Recall: 0.7039
F1 Score: 0.7091

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.69      0.75       114
           1       0.57      0.72      0.64        65

    accuracy                           0.70       179
   macro avg       0.69      0.71      0.69       179
weighted avg       0.73      0.70      0.71       179


Confusion Matrix:
[[79 35]
 [18 47]]
RF
Accuracy: 0.8436
Precision: 0.8436
Recall: 0.8436
F1 Score: 0.8436

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       114
           1       0.78      0.78      0.78        65

    accuracy                           0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179


Confusion Matrix:
[[100  14]
 [ 14  51]]
LR
Accuracy: 0.8156
Precision: 0.8136
Recall: 0.8156
F1 Score: 0.8139

Classif

In [14]:
#hyper parameter tunning for random forest
Rf_clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [15]:
param_dict = {
    'n_estimators': [10, 50, 100, 200],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'bootstrap': [True, False]

}

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
grid_sc = GridSearchCV(RandomForestClassifier(),
                       param_grid = param_dict,
                       scoring='accuracy',
                       n_jobs=-1,
                       verbose=10)

In [18]:
grid_sc.fit(X_train, y_train)

Fitting 5 folds for each of 1728 candidates, totalling 8640 fits


GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10, 20, 30],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [10, 50, 100, 200]},
             scoring='accuracy', verbose=10)

In [22]:
grid_sc.best_score_

0.8398502905545158

In [23]:
grid_sc.best_params_

{'bootstrap': True,
 'criterion': 'entropy',
 'max_depth': 30,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 10,
 'n_estimators': 50}

In [21]:
grid_sc.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=30, max_features='log2',
                       min_samples_split=10, n_estimators=50)

In [26]:
LR_new = grid_sc.best_estimator_

In [27]:
LR_new_accuracy = evaluate(LR_new, X_test, y_test)

Accuracy: 0.8436
Precision: 0.8448
Recall: 0.8436
F1 Score: 0.8441

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.87      0.88       114
           1       0.78      0.80      0.79        65

    accuracy                           0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179


Confusion Matrix:
[[99 15]
 [13 52]]


In [28]:
evaluate(LR_clf, X_test, y_test)


Accuracy: 0.8156
Precision: 0.8136
Recall: 0.8156
F1 Score: 0.8139

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       114
           1       0.77      0.71      0.74        65

    accuracy                           0.82       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.81      0.82      0.81       179


Confusion Matrix:
[[100  14]
 [ 19  46]]


0.8156424581005587

In [31]:
# Assign the best estimator found by GridSearchCV to a new variable (Rn_New)
Rn_New = grid_sc.best_estimator_

# Make predictions on the test set using the best estimator (Rn_New)
val_predictions = Rn_New.predict(X_test)

# Calculate the accuracy of the predictions
val_accuracy = accuracy_score(y_test, val_predictions)
print(f"\nValidation Accuracy: {val_accuracy:.4f}")


Validation Accuracy: 0.8436


In [32]:
mse = mean_squared_error(y_test, val_predictions)
print(f"Mean Squared Error (MSE): {mse:.4f}")

Mean Squared Error (MSE): 0.1564


In [33]:
# Clean test set for predictions
test_data = pd.read_csv("test.csv")
print(test_data.head())
print(test_data.dtypes)

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S  
PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          

In [34]:
test_data = test_data.drop(['Name','Ticket','Cabin'], axis=1)
test_data.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)
test_data['Age'].fillna(test_data['Age'].mean(), inplace=True)
test_data['Fare'].fillna(test_data['Fare'].mean(), inplace=True)
test_data['Embarked'].fillna(test_data['Embarked'].mode()[0], inplace=True)
print(test_data.dtypes)

PassengerId      int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object


In [35]:
test_data.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [38]:
# set to csv

# Predictions on test set
test_predictions = Rn_New.predict(test_data)

# Create submission DataFrame
submission_df = pd.DataFrame({
    "PassengerId": test_passenger_ids,
    "Survived": test_predictions
})

submission_df.head(10)

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0

In [39]:
# # Save submission file
submission_df.to_csv("Advanced_model_results.csv", index=False)

print("Submission file saved successfully.")

Submission file saved successfully.


In [40]:
# create pikel file
import pickle

pickle.dump(Rn_New, open('./model.h5', 'wb'))

# Pickle file chechk


In [41]:
import pickle
model = pickle.load(open('model.h5', 'rb'))


In [42]:
import pandas as pd

In [43]:
# PassengerId    0
# Pclass         0
# Sex            male: 0 female:1
# Age            0
# SibSp          0
# Parch          0
# Fare           0
# Embarked       'S':0,'C':1,'Q':2

pred = model.predict([[1,3,0,22.0,1,0,7.25,0]])
if pred[0] == 0:
  print("So Sorry! Not survived")
else:
  print("Survived")

So Sorry! Not survived


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
